# Generated by Django 3.0.5 on 2020-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200516_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
